project:
  type: website
  output-dir: docs

website:
  title: "Luke's Personal Website"
  navbar:
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/luke-epp-s/
      - icon: medium
        href: https://medium.com/@lukeepp
      - icon: github
        href: https://github.com/luke-epp

format:
  html:
    theme:
      dark: [darkly, custom.scss]
    css: styles.css
    toc: true
    page-layout: full
    code-copy: true
    code-overflow: wrap
    highlight-style: github-dark 