---
title: "Project Euler Fifty"
author: "Luke"
date: "2024-07-13"
categories: [R, Project Euler]
---

## Project Euler Four

[Question](https://projecteuler.net/problem=50)


<p>The prime $41$, can be written as the sum of six consecutive primes:</p>
$$41 = 2 + 3 + 5 + 7 + 11 + 13.$$
<p>This is the longest sum of consecutive primes that adds to a prime below one-hundred.</p>
<p>The longest sum of consecutive primes below one-thousand that adds to a prime, contains $21$ terms, and is equal to $953$.</p>
<p>Which prime, below one-million, can be written as the sum of the most consecutive primes?</p>


Reading this, we know we will need two functions, one to generate a series of consecutive primes and another function to determine if a number is prime.

```{cpp}
#include <cmath>
#include <Rcpp.h>
#include <vector>
using namespace Rcpp;

// [[Rcpp::export]]
bool IsPrime(int n) {
    if (n <= 1) return false;           // handle 0 and 1
    if (n == 2) return true;            // 2 is prime
    if (n % 2 == 0) return false;       // even numbers > 2 aren't prime

    int sqrt_n = static_cast<int>(std::sqrt(n));
    for (int i = 3; i <= sqrt_n; i += 2) {  // skip even numbers
        if (n % i == 0) {
            return false;
        }
    }
    return true;
}

```

Okay, now test out our super basic primality test

```{r}
Rcpp::sourceCpp("/Users/lukeepp/project-euler/pe/pe2.cpp")
system.time(print(even_fibonaccis_arr()))

```

The syntax and piping makes collapse really nice to use, the cross join is how we get a vectorized approach and are able to leverage collapse for subsequent operations. Fast and clean.